//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_PDK
    {
        public long Ma_CTPDK { get; set; }
        public string Ma_PDK { get; set; }
        public string MaPhong { get; set; }
        public Nullable<int> SoNguoiLon { get; set; }
        public Nullable<int> SoTreEm { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<bool> TrangThai_TT { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual PHIEU_DK PHIEU_DK { get; set; }
    }
}
