//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HD
    {
        public long Ma_CTHD { get; set; }
        public string MaHD { get; set; }
        public string Ma_PDK { get; set; }
        public Nullable<long> TienPhong { get; set; }
        public Nullable<long> TienDV { get; set; }
        public Nullable<long> TienCoc { get; set; }
        public Nullable<long> TienPhatSinh { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHIEU_DK PHIEU_DK { get; set; }
    }
}
