//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUCHI
    {
        public long Ma_CTPC { get; set; }
        public string MaPC { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual PHIEUCHI PHIEUCHI { get; set; }
    }
}
