//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public DICHVU()
        {
            this.DICHVU_SD = new HashSet<DICHVU_SD>();
        }
    
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public Nullable<long> GiaDV { get; set; }
    
        public virtual ICollection<DICHVU_SD> DICHVU_SD { get; set; }
    }
}
