//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGIA
    {
        public DONGIA()
        {
            this.LOAIPHONGs = new HashSet<LOAIPHONG>();
        }
    
        public long MaGia { get; set; }
        public Nullable<long> Gia { get; set; }
    
        public virtual ICollection<LOAIPHONG> LOAIPHONGs { get; set; }
    }
}
