//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public string MaHD { get; set; }
        public string IDNguoiDung { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<long> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual QL_NguoiDung QL_NguoiDung { get; set; }
    }
}
