//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_DK
    {
        public PHIEU_DK()
        {
            this.CHITIET_PDK = new HashSet<CHITIET_PDK>();
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public string Ma_PDK { get; set; }
        public string IDNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string MaKH { get; set; }
        public Nullable<long> TienCoc { get; set; }
        public Nullable<long> TrangThai { get; set; }
    
        public virtual ICollection<CHITIET_PDK> CHITIET_PDK { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual QL_NguoiDung QL_NguoiDung { get; set; }
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
    }
}
