//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.CHITIET_PDK = new HashSet<CHITIET_PDK>();
            this.DICHVU_SD = new HashSet<DICHVU_SD>();
        }
    
        public string MaPhong { get; set; }
        public string MaLP { get; set; }
        public string HienTrang { get; set; }
        public string So_DT_Phong { get; set; }
        public Nullable<int> SoNguoi_Max { get; set; }
        public string GhiChu { get; set; }
        public Nullable<long> TienPhatSinh { get; set; }
    
        public virtual ICollection<CHITIET_PDK> CHITIET_PDK { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual ICollection<DICHVU_SD> DICHVU_SD { get; set; }
    }
}
