//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_NguoiDungNhomNguoiDung
    {
        public string IDNguoiDung { get; set; }
        public string MaNhomNguoiDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual QL_NguoiDung QL_NguoiDung { get; set; }
        public virtual QL_NhomNguoiDung QL_NhomNguoiDung { get; set; }
    }
}
