//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VICTORY_HOTEL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VictoryHotelEntities : DbContext
    {
        public VictoryHotelEntities()
            : base("name=VictoryHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIET_PDK> CHITIET_PDK { get; set; }
        public DbSet<CHITIET_PHONG> CHITIET_PHONG { get; set; }
        public DbSet<CHITIETPHIEUCHI> CHITIETPHIEUCHIs { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<DM_ManHinh> DM_ManHinh { get; set; }
        public DbSet<DONGIA> DONGIAs { get; set; }
        public DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public DbSet<MOTA_PHONG> MOTA_PHONG { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHIEUCHI> PHIEUCHIs { get; set; }
        public DbSet<PHIEUKIEMKE> PHIEUKIEMKEs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<QL_NguoiDung> QL_NguoiDung { get; set; }
        public DbSet<QL_NguoiDungNhomNguoiDung> QL_NguoiDungNhomNguoiDung { get; set; }
        public DbSet<QL_NhomNguoiDung> QL_NhomNguoiDung { get; set; }
        public DbSet<QL_PhanQuyen> QL_PhanQuyen { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<PHIEU_DK> PHIEU_DK { get; set; }
        public DbSet<DICHVU_SD> DICHVU_SD { get; set; }
        public DbSet<CHITIET_HD> CHITIET_HD { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
    }
}
